version: '3.7'
services:
  web:
    image: myapp-web:1.0.0
    build: ./nginx
    networks:
      - overlay
    deploy:
      restart_policy:
        condition: on-failure
      mode: global
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
  app:
    image: myapp-app:1.0.0
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        VERSION: 1.0.0
        COLOR: green
    networks:
      - overlay
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  overlay:
